# Generated by Django 3.1.3 on 2020-11-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LSP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('duplicate', models.IntegerField(default=0)),
                ('div_1', models.CharField(max_length=1000)),
                ('div_2', models.CharField(max_length=1000)),
                ('div_3', models.CharField(max_length=1000)),
                ('div_4', models.CharField(max_length=1000)),
                ('file_name', models.CharField(max_length=1000)),
                ('file_dir', models.CharField(max_length=1000)),
                ('value', models.CharField(max_length=1000)),
            ],
        ),
    ]
